// <auto-generated />
using System;
using ApuracaoPontoSimples.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApuracaoPontoSimples.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315172053_RemoveTimeCardYearMonth")]
    partial class RemoveTimeCardYearMonth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DayEntryId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("Hours")
                        .HasColumnType("interval");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DayEntryId")
                        .IsUnique();

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.DayCalculation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("AcumuladoSemana")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("Apuracao")
                        .HasColumnType("interval");

                    b.Property<double?>("ApuracaoConv")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("BancoHoras")
                        .HasColumnType("interval");

                    b.Property<double?>("BancoHorasConv")
                        .HasColumnType("double precision");

                    b.Property<Guid>("DayEntryId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("FechamentoSemanaNegativo")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("FechamentoSemanaPositivo")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("HorasDsrFeriado")
                        .HasColumnType("interval");

                    b.Property<double?>("HorasDsrFeriadoConv")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("HorasExtras")
                        .HasColumnType("interval");

                    b.Property<double?>("HorasExtrasConv")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("HorasNegativas")
                        .HasColumnType("interval");

                    b.Property<double?>("HorasNegativasConv")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("HorasNoturnas")
                        .HasColumnType("interval");

                    b.Property<double?>("HorasNoturnasConv")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan?>("HorasPositivas")
                        .HasColumnType("interval");

                    b.Property<double?>("HorasPositivasConv")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DayEntryId")
                        .IsUnique();

                    b.ToTable("DayCalculation");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.DayEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HolidayType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSaturday")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSunday")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TimeCardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeCardId");

                    b.ToTable("DayEntries");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pis")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employers");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.ScheduleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("DailyHours")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("DailyLimit")
                        .HasColumnType("interval");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("NightEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("NightStart")
                        .HasColumnType("interval");

                    b.Property<bool>("SaturdayCountsAsBank")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("SaturdayHours")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ToleranceEntry")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("ToleranceExit")
                        .HasColumnType("interval");

                    b.Property<bool>("UseDailyHoursAsY13")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan?>("WeeklyHours")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.TimeCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeCards");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.TimeCardTotals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("ApuracaoConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("ApuracaoTotal")
                        .HasColumnType("interval");

                    b.Property<double>("BancoHorasConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("BancoHorasTotal")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("FechamentoSemanaNegativoTotal")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("FechamentoSemanaPositivoTotal")
                        .HasColumnType("interval");

                    b.Property<double>("HorasDsrFeriadoConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("HorasDsrFeriadoTotal")
                        .HasColumnType("interval");

                    b.Property<double>("HorasExtrasConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("HorasExtrasTotal")
                        .HasColumnType("interval");

                    b.Property<double>("HorasNegativasConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("HorasNegativasTotal")
                        .HasColumnType("interval");

                    b.Property<double>("HorasNoturnasConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("HorasNoturnasTotal")
                        .HasColumnType("interval");

                    b.Property<double>("HorasPositivasConvTotal")
                        .HasColumnType("double precision");

                    b.Property<TimeSpan>("HorasPositivasTotal")
                        .HasColumnType("interval");

                    b.Property<Guid>("TimeCardId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TimeCardId")
                        .IsUnique();

                    b.ToTable("TimeCardTotals");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Absence", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.DayEntry", null)
                        .WithOne("Absence")
                        .HasForeignKey("ApuracaoPontoSimples.Domain.Entities.Absence", "DayEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.DayCalculation", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.DayEntry", null)
                        .WithOne("Calculation")
                        .HasForeignKey("ApuracaoPontoSimples.Domain.Entities.DayCalculation", "DayEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.DayEntry", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.TimeCard", null)
                        .WithMany("Days")
                        .HasForeignKey("TimeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ApuracaoPontoSimples.Domain.ValueObjects.TimeInterval", "Interval1", b1 =>
                        {
                            b1.Property<Guid>("DayEntryId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan?>("End")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan?>("Start")
                                .HasColumnType("interval");

                            b1.HasKey("DayEntryId");

                            b1.ToTable("DayEntries");

                            b1.WithOwner()
                                .HasForeignKey("DayEntryId");
                        });

                    b.OwnsOne("ApuracaoPontoSimples.Domain.ValueObjects.TimeInterval", "Interval2", b1 =>
                        {
                            b1.Property<Guid>("DayEntryId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan?>("End")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan?>("Start")
                                .HasColumnType("interval");

                            b1.HasKey("DayEntryId");

                            b1.ToTable("DayEntries");

                            b1.WithOwner()
                                .HasForeignKey("DayEntryId");
                        });

                    b.OwnsOne("ApuracaoPontoSimples.Domain.ValueObjects.TimeInterval", "Interval3", b1 =>
                        {
                            b1.Property<Guid>("DayEntryId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan?>("End")
                                .HasColumnType("interval");

                            b1.Property<TimeSpan?>("Start")
                                .HasColumnType("interval");

                            b1.HasKey("DayEntryId");

                            b1.ToTable("DayEntries");

                            b1.WithOwner()
                                .HasForeignKey("DayEntryId");
                        });

                    b.Navigation("Interval1")
                        .IsRequired();

                    b.Navigation("Interval2")
                        .IsRequired();

                    b.Navigation("Interval3")
                        .IsRequired();
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.ScheduleConfig", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.Employee", null)
                        .WithOne("Schedule")
                        .HasForeignKey("ApuracaoPontoSimples.Domain.Entities.ScheduleConfig", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.TimeCard", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.TimeCardTotals", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Domain.Entities.TimeCard", null)
                        .WithOne("Totals")
                        .HasForeignKey("ApuracaoPontoSimples.Domain.Entities.TimeCardTotals", "TimeCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ApuracaoPontoSimples.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.DayEntry", b =>
                {
                    b.Navigation("Absence");

                    b.Navigation("Calculation");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ApuracaoPontoSimples.Domain.Entities.TimeCard", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Totals");
                });
#pragma warning restore 612, 618
        }
    }
}
